#SPDX-License-Identifier: MIT-0
---
# handlers file for postres
- name: restart postgresql
  ansible.builtin.service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_restarted_state }}"
    sleep: 5
