---
# tasks file for postres
- include_tasks: variables.yml
  when: ansible_distribution | lower == 'almalinux' 

- include_tasks: setup-packages.yml

- include_tasks: initialize.yml

- name: Ensure Postgresql is started and enabled on boot
  service:
    name: "{{ postgresql_daemon }}"
    state: "{{ postgresql_service_state }}"
    enabled: "{{ postgresql_service_enabled }}"

- import_tasks: users.yml
